dist: bionic
language: cpp
sudo: required
compiler:
  - gcc
  - clang
os:
  - linux
script:
  - cd $TRAVIS_BUILD_DIR
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - cmake --build . --config Release
  - ./flatjson
  - eval $CXX -std=c++11 -O2 -D__FLATJSON__CHILDS_TYPE=std::uint16_t -UNDEBUG parsetest.cpp -o parsetest
  - ./parsetest canada.json
  - ./parsetest citm_catalog.json
  - ./parsetest jeopardy.json
  - ./parsetest twitter.json
