dist: bionic
language: cpp
sudo: required
compiler:
  - gcc
  - clang
os:
  - linux
script:
  - cd $TRAVIS_BUILD_DIR
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - cmake --build . --config Release
  - ./flatjson
  - eval $CXX -O2 parsetest.cpp -o parsetest
  - ./parsetest canada.json
  - ./parsetest citm_catalog.json
  - ./parsetest jeopardy.json
  - ./parsetest twitter.json
