dist: bionic
language: cpp
sudo: required
compiler:
  - gcc
  - clang
os:
  - linux
before_install:
  - echo "CC=$CC"
  - echo "CXX=$CXX"
script:
  - cd $TRAVIS_BUILD_DIR
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - ls
  - ./flatjson
  - eval $CXX -O2 parsetest.cpp -o parsetest
  - ./parsetest canada.json && ./parsetest citm_catalog.json && ./parsetest jeopardy.json && ./parsetest twitter.json
